### ISSUE TITLE
Error: Jest: Got error running globalSetup

### ISSUE THREAD

**Issue by Liam1337** [RuiSiang/PoW-Shield#316]
![image](https://user-images.githubusercontent.com/94720916/164455211-5bad5b2e-73a8-45f6-861b-72eb21a74442.png)

Hey, Possible to get help? 
You can message me also on discord Liam1337#3504

**Comment by RuiSiang** [comment]
Hi, different environments might have different issues. If possible, please use the docker images until we can understand what is causing the issue. It's impossible for us to help you if all you provide is a screenshot.

Please include environmental information (such as OS, node versions, etc)

**Comment by Liam1337** [comment]
Hi, I use Ubuntu 20.04 & the node version v12.22.11.
![image](https://user-images.githubusercontent.com/94720916/164727080-d5fdb7f8-c0c0-4e3f-a7b1-0605520587e5.png)

**Comment by RuiSiang** [comment]
There is a minimum version in prerequisites on Nodejs and Docker versions. Node v12 won't work.

And btw, there's a permission problem with your Docker installation, OCI runtime issues are not a relevant problem in this project since we're built on top of Docker. Go check out Docker's troubleshooting and how to properly set permissions on relevant forums or repos.
